name: Build and Test

on:    
  pull_request:
    branches: [ master ]
    
    paths-ignore:
      - '**/.md'
      - '**/.txt'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Avoid shallow clone so NBGV can do its work.
          submodules: 'recursive'
      - name: Set version
        uses: dotnet/nbgv@v0.4.2
        with:
          setAllVars: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=true
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=true
